# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24d7e29fa1e960463239394dbc853cf3e00d908971a0177eec97e6edacdcc7f8c646ae8f48f1a12c62f183af8cb97e19bad8a48b3735a61d560af9abd7a5799

test:
  secret_key_base: 3f9d7dbe049fb719af611eb38378e08fe47c0afe721a2c3732c69230f06076a6b5205a3efe4817068e6d5b7a47ac131cb8e9d60d8eaefd7b133cc7335f2b016b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
